fail_fast: true
default_install_hook_types:
  - pre-commit
  - commit-msg

{% raw -%}
repos:
  # =============================== branch names =========================== {{{

  - repo: local
    hooks:
      - id: branch_name_check
        stages: [commit]
        name: branch_name_check
        language: system
        entry: ./scripts/branch_names.sh

  # }}}


  # =============================== Default Hooks ========================== {{{

  # Clean notebook output (should run before large file check)
  - repo: https://github.com/srstevenson/nb-clean
    rev: 3.2.0
    hooks:
      - id: nb-clean

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # git
      - id: no-commit-to-branch # enforce no direct commit to master also locally.
      - id: check-added-large-files # disallow large files, use lfs instead.
        args: ["--maxkb=1000"]

        # general
      - id: trailing-whitespace
      - id: check-executables-have-shebangs

        # python
      - id: requirements-txt-fixer
      - id: debug-statements # do not leave breakpoints in python

        # config files
      - id: check-json
        exclude: "notebooks/.*"

      - id: pretty-format-json
        args: ["--autofix"]
        exclude: "notebooks/.*"

      - id: check-yaml
      - id: check-toml
      - id: check-xml

  # }}}

  # ================================== Python ============================== {{{

  # linting
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.2
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]

  # }}}

  # ============================== commit messages ========================= {{{

  # enforce conventional commits
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [push]

  # }}}
{% endraw %}